# Generated by Django 5.0.2 on 2024-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_service_image_url_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Temporary Address'),
            preserve_default=False,
        ),
    ]
